src/EnergyPi.Web/Controllers/TodayController.cs
using System;
using EnergyPi.Web.Builders;
using EnergyPi.Web.DataServices;
using EnergyPi.Web.Extensions;
using EnergyPi.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EnergyPi.Web.Controllers
{
    [Authorize]
    public class TodayController : Controller
    {
        // Dependencies
        private readonly ITodayViewModelBuilder _todayViewModelBuilder;
        private readonly IEnergyLogsDataService _energyLogsDataService;
        private readonly IWeatherLogsDataService _weatherLogsDataService;

        // Constructors
        public TodayController(ITodayViewModelBuilder todayViewModelBuilder,
                               IEnergyLogsDataService energyLogsDataService,
                               IWeatherLogsDataService weatherLogsDataService)
        {
            _todayViewModelBuilder = todayViewModelBuilder;
            _energyLogsDataService = energyLogsDataService;
            _weatherLogsDataService = weatherLogsDataService;
        }

        // Private Methods
        private TodayViewModel GetTodayViewModelInternal()
        {
            var startDate = DateTimeExtensions.GetFirstDayOfMonth(DateTime.Now);
            var endDate = DateTimeExtensions.GetFirstDayOfNextMonth(DateTime.Now);

            var currentMonthsEnergyLogs = _energyLogsDataService.GetRecordsForDateRange(startDate, endDate);
            var currentMonthsWeatherLogs = _weatherLogsDataService.GetRecordsForDateRange(startDate, endDate);

            var todayViewModel = _todayViewModelBuilder.BuildTodayViewModel(currentMonthsEnergyLogs, currentMonthsWeatherLogs);
            return todayViewModel;
        }

        // View Methods
        public IActionResult Index()
        {
            var todayViewModel = GetTodayViewModelInternal();
            return View(todayViewModel);
        }

        // API Methods
        [HttpGet]
        public JsonResult GetTodayViewModel()
        {
            var todayViewModel = GetTodayViewModelInternal();
            return Json(todayViewModel);
        }

    }
}

src/EnergyPi.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EnergyPi.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Today" asp-action="Index">EnergyPi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Today" asp-action="Index">Today</a>
                        </li>
                        <li>
                            @Html.ActionLink("History", "Index", "History", new { date = DateTime.Now.AddDays(-1).Date }, new { @class="nav-link text-dark" })
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EnergyPi
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js" integrity="sha512-rmZcZsyhe0/MAjquhTgiUcb4d9knaFc7b5xAfju483gbEXTkeJRUMIPk6s3ySZMYUHEcjKbjLjyddGWMrNEvZg==" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>